sudo apt-get install build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev
sudo -i R

install.packages('devtools')
install.packages('dplyr')
install.packages('tidyr')
install.packages('ggplot2')
install.packages('readxl')
install.packages('XML')
install.packages('lubridate')
install.packages('doParallel')
install.packages('profvis')
install.packages('readr')
install.packages('knitr')
install.packages('xlsx')
install.packages('R.utils')
install.packages('stringr')
install.packages('mgcv')
install.packages('parallel')
install.packages('RSQLite')
install.packages('tidyverse')
install.packages('ggrepel')
install.packages('lme4')
install.packages('broom')
install.packages('RSQLite')
install.packages('etl')
install.packages("zoo")
devtools::install_github("BillPetti/baseballr")
